name: Python Checkers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3.9.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.12
      - name: Install pipenv
        run: pip install poetry
      - name: Run tests
        run: |
          poetry install
          poetry run pytest
